clusters:
  default:
    master:
      token: ""
      channel_id: ""

shifts:
  - state: "active"
    duration:
      base: 7200
      variation: 1800
  - state: "dormant"
    duration:
      base: 1800
      variation: 1800
  - state: "active"
    duration:
      base: 7200
      variation: 3600
  - state: "dormant"
    duration:
      base: 32400
      variation: 3600

features:
  commands:
    pray: true
    hunt: true

  custom_commands:
  auto_sell:
    enable: false
    items:
      - item: "all"
  log_to_file: true
  verbose_log_to_stdout: true
  debug: false

compatibility:
    hunt: 15
    sell: 3
    gift: 26
    share: 13
  await_response_timeout: 7

suspicion_avoidance:
  typing:
    variation: 250
    speed: 450
  message_delay:
    base: 100
    variation: 400
